apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - user-workload-monitoring.yaml
  - tempo-multitenant.yaml
  - rbac.yaml
patches:
  - path: patches/otel-tempo-tenant.yaml
