version: "2"
run:
  timeout: 10m
linters:
  default: standard
  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - gocritic
    - gocyclo
    - goprintffuncname
    - govet
    - ineffassign
    - iotamixing
    - misspell
    - modernize
    - nakedret
    - nolintlint
    - staticcheck
    - unconvert
    - unused
    - whitespace
    - nilerr
  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/rhobs/obs-mcp
