# creats a 1 pod deployment for the cluster-health-analyzer
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: obs-mcp
  name: obs-mcp
  namespace: openshift-lightspeed
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: obs-mcp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: obs-mcp
    spec:
      serviceAccountName: obs-mcp-thanos-querier
      automountServiceAccountToken: true
      containers:
        - name: obs-mcp-server
          image: "quay.io/inecas_rh/obc-mcp:latest"
          imagePullPolicy: Always
          args:
            - --listen
            - :8085
            - --auth-mode
            - serviceaccount
            - --toolsets
            - metrics,traces
          env:
            - name: PROMETHEUS_URL
              value: "https://thanos-querier.openshift-monitoring.svc.cluster.local:9091/"
            - name: ALERTMANAGER_URL
              value: "https://alertmanager-main.openshift-monitoring.svc.cluster.local:9094"
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
          ports:
            - containerPort: 8085
              name: mcp
          terminationMessagePolicy: FallbackToLogsOnError
